[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "featly"
version = "0.1.0"
description = "A lightweight unified feature development framework"